#!/usr/bin/bash

# get the current working directory; $PWD
# get users home directory; $HOME
echo $PWD
echo $HOME

# check for lib folder 
if [ -d $HOME"/lib" ]
then
    echo $HOME"/lib"
    # removing old version on edts
    if [ -d $HOME"/lib/edts" ]
    then
        echo $HOME"/lib/edts"
        if [ $PWD != $HOME"/lib/edts" ]
        then
           rm -rf $HOME"/lib/edts"
        fi
    fi    
else
    mkdir -p $Home"/lib"
    mkdir -p $HOME"/lib/edts"
fi

# copy code into the lib folder
if [ $PWD != $HOME"/lib/edts" ]
then
    cp -r $PWD $HOME"/lib/edts"
fi    

# check for bin folder
if [ ! -d $HOME"/bin" ]
then 
    # create link to code in bin directory 
    mkdir -p $HOME"/bin"
fi  

# compling fortran code
module load GCC/7.1.0-2.28
gfortran $HOME/lib/edts/ConfMaker.f -O3 -o $HOME/lib/edts/ConfMaker -ffixed-line-length-132
module unload GCC/7.1.0-2.28

# making perl code an executable 
module load Perl/5.24.0-GCC-5.4.0-2.26
chmod +x $HOME/lib/edts/*.pl
chmod +x $HOME/lib/edts/lib/*.pl
module unload Perl/5.24.0-GCC-5.4.0-2.26

ln -sf $HOME/lib/edts/ConfMaker $HOME/bin/ConfMaker
#NOTE change to rotabond.pl when added. 
ln -sf $HOME/lib/edts/EDTS_autorun_part1.pl $HOME/bin/EDTS
ln -sf $HOME/lib/edts/sub/restartjob.sh $HOME/bin/RESTART_EDTS


#if [ $PWD != $HOME"/lib/edts" ] 
#then
#    echo "does this work"
#    dir=$(echo $PWD)
#    echo $dir
#    cd $HOME
#    echo $PWD
#    #rm -rf $dir
#fi

# END FILE
